# Site settings
title: The Reprogram
name: The Reprogram
email: your-email@domain.com
description: "A blog about programming and software development by Richard Flores."
url: http://richardrflores.com
# baseurl: /blog
category_archive:
        path: /category

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title.html

# This will require each of these plugins automatically.
gems:
  - jekyll-admin